version: "3.8"
services:
  backend:
    platform: linux/amd64
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./printdata
        target: /django/ticketpdf
      # - type: volume
      #   source: ./backend
      #   target: /django
    depends_on:
      db:
        condition: service_healthy 
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deploy-static 
    ports: 
      - 3000:80
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

# volumes:
#   backend: