# Generated by Django 4.0.6 on 2022-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wait', models.IntegerField(default=0)),
                ('called', models.BooleanField(default=False)),
            ],
        ),
    ]
