# Generated by Django 4.0.6 on 2022-07-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticketing.counter'),
        ),
    ]
